"""create initial gaa analytics schema

Revision ID: ce6f8924b21c
Revises:
Create Date: 2026-08-31 11:27:39.197158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6f8924b21c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_code', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('competition', sa.String(length=150), nullable=True),
    sa.Column('round', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('home_team', sa.String(length=150), nullable=False),
    sa.Column('away_team', sa.String(length=150), nullable=False),
    sa.Column('home_score', sa.String(length=50), nullable=True),
    sa.Column('away_score', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_code')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=150), nullable=False),
    sa.Column('squad_number', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_name')
    )
    op.create_table('kickout_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('kickout_type', sa.String(length=20), nullable=False),
    sa.Column('taken', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('clean_wins', sa.Integer(), nullable=False),
    sa.Column('break_wins', sa.Integer(), nullable=False),
    sa.Column('free_wins', sa.Integer(), nullable=False),
    sa.Column('sideline_wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team', 'period', 'kickout_type', name='uq_kickout_match_team_period_type')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opponent', sa.String(length=150), nullable=True),
    sa.Column('home_away', sa.String(length=20), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('squad_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('minutes_played', sa.Float(), nullable=True),
    sa.Column('possessions', sa.Integer(), nullable=False),
    sa.Column('handpasses_total', sa.Integer(), nullable=False),
    sa.Column('handpasses_1h', sa.Integer(), nullable=False),
    sa.Column('handpasses_2h', sa.Integer(), nullable=False),
    sa.Column('handpasses_completed', sa.Integer(), nullable=False),
    sa.Column('footpasses_total', sa.Integer(), nullable=False),
    sa.Column('footpasses_1h', sa.Integer(), nullable=False),
    sa.Column('footpasses_2h', sa.Integer(), nullable=False),
    sa.Column('footpasses_completed', sa.Integer(), nullable=False),
    sa.Column('incomplete_passes', sa.Integer(), nullable=False),
    sa.Column('kickouts_won', sa.Integer(), nullable=False),
    sa.Column('breaking_balls_won', sa.Integer(), nullable=False),
    sa.Column('turnovers_won', sa.Integer(), nullable=False),
    sa.Column('turnovers_lost', sa.Integer(), nullable=False),
    sa.Column('frees_won', sa.Integer(), nullable=False),
    sa.Column('frees_conceded', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('points_play', sa.Integer(), nullable=False),
    sa.Column('points_free', sa.Integer(), nullable=False),
    sa.Column('points_45', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('two_pointers', sa.Integer(), nullable=False),
    sa.Column('shot_attempts', sa.Integer(), nullable=False),
    sa.Column('scores', sa.Integer(), nullable=False),
    sa.Column('shot_conversion_pct', sa.Float(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('black_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_player_match_stats_match_player')
    )
    op.create_table('scoring_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('scores', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team', 'source', name='uq_scoring_source_match_team_source')
    )
    op.create_table('shooting_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('shot_type', sa.String(length=50), nullable=False),
    sa.Column('shots_taken', sa.Integer(), nullable=False),
    sa.Column('shots_scored', sa.Integer(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('shorts', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team', 'period', 'shot_type', name='uq_shooting_match_team_period_type')
    )
    op.create_table('team_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.Column('opponent', sa.String(length=150), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('two_pointers', sa.Integer(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('shorts', sa.Integer(), nullable=False),
    sa.Column('kickouts_won', sa.Integer(), nullable=False),
    sa.Column('kickouts_lost', sa.Integer(), nullable=False),
    sa.Column('forced_turnovers', sa.Integer(), nullable=False),
    sa.Column('unforced_turnovers', sa.Integer(), nullable=False),
    sa.Column('frees_conceded', sa.Integer(), nullable=False),
    sa.Column('breaking_ball_won', sa.Integer(), nullable=False),
    sa.Column('attacks', sa.Integer(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('total_scores', sa.Integer(), nullable=False),
    sa.Column('shots_play', sa.Integer(), nullable=False),
    sa.Column('scores_play', sa.Integer(), nullable=False),
    sa.Column('shots_placed', sa.Integer(), nullable=False),
    sa.Column('scores_placed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team', name='uq_team_match_stats_match_team')
    )
    op.create_table('turnover_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('turnovers_won_forced', sa.Integer(), nullable=False),
    sa.Column('turnovers_won_unforced', sa.Integer(), nullable=False),
    sa.Column('turnovers_lost_forced', sa.Integer(), nullable=False),
    sa.Column('turnovers_lost_unforced', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team', 'period', name='uq_turnover_match_team_period')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('turnover_stats')
    op.drop_table('team_match_stats')
    op.drop_table('shooting_detail')
    op.drop_table('scoring_sources')
    op.drop_table('player_match_stats')
    op.drop_table('kickout_stats')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
